var path = '//'+location.host;
var tpath = /mogoroom-renterpc/.test(location.href)?'/mogoroom-renterpc/pages/templates/':'/pages/templates/';
var templatePath = location.protocol+"//"+location.host+tpath;
require.config({
    baseUrl:/mogoroom-renterpc/.test(location.href)?'/mogoroom-renterpc/static/js':'/static/js/',
    map: {
        '*': {
            'css': 'css',
            'text':'text'
        }
    },
    shim:{
    	'BMapLib.RichMarker':['BMap'],
    	'jquery.validate': ['jquery'],
    	'scrollpagination': ['jquery'],
    	'jquery.cookie':['jquery'],
        'touchWipe':['zepto'],
        'bootstrap':['jquery','placeholder'],
        'placeholder':['jquery'],
        'calendar':['css!../plugins/calendar/css/calendar-date.css','jquery'],
        'template':['jquery'],
        'jqueryui':['css!../plugins/jqueryui/css/jquery-ui.min.css','jquery'],
        'validate.form':['jquery','validate'],
        'autocomplete':['jquery','bootstrap'],
        'flexslider':['jquery'],
        'lofSlider':['css!../plugins/slider/lof-slider.css','jquery','easing'],
        'popwin':['css!../plugins/popwin/css/popWin.css','jquery'],
        'mouseWheel':['jquery'],
        'smoothScroll':['jquery','mouseWheel'],
        'fancybox-thumbs':['jquery','fancybox'],
        'datetimepicker':['css!../plugins/bootstrapv3/bootstrap/css/bootstrap-datetimepicker.css','jquery','bootstrap'],
        'mslider':['css!../plugins/mslider/css/mslider.css','jquery'],
        'swiper':['css!../plugins/swiper/css/swiper.min.css'],
        'iswiper':['css!../plugins/iswiper/css/idangerous.swiper.css'],
        'iswiper.scroll':['css!../plugins/iswiper/css/idangerous.swiper.scrollbar.css','iswiper'],
        'swiper.animate':['css!../css/animate.min.css'],
        'mySwiper':['css!../css/mySwiper.css'],
        'datetimepickerCN':['datetimepicker'],
        'jasmine':{
            deps:['css!../jasmine/lib/jasmine-core/jasmine.css'],
            exports: 'window.jasmineRequire'
        },
        'jasmine-html': {
            deps: ['jasmine'],
            exports: 'window.jasmineRequire'
        },
        'boot':{
            deps:['jasmine','jasmine-html'],
            exports:'window.jasmineRequire'
        },
        'jquery-ui.slider':['jquery'],
        'playerSpec':['jasmine','jasmine-html','player'],
        'mySwiperSpec':['boot'],
         'stellar':['jquery']
    },
	paths: {
		BMap:'http://api.map.baidu.com/getscript?v=2.0&ak=kKPe6mqjoQ6Ucs8WiqpnASf5',
		'BMapLib.RichMarker':'RichMarker',
		data:'../data',
		tp:'../templates',
        "jquery": "jquery-1.9.1",
		"jquery.validate":"jquery.validate.min",
		"scrollpagination":"scrollpagination",
        'rc':"resource",
        "zepto": "zepto.min",
        "touchWipe": "zepto.touchWipe",
        'template':'template',
        'store':'store',
        'history':'history/history',
        "calendar":"calendar",
        "validate":"jquery.validate.min",
        'placeholder':'jquery.placeholder.min',
        "validate.form":"validate.form",
        "md5":'jquery.md5',
        "map":'mapScript',
        'antbridge':'antbridge.min',
        "jquery-1.11.3": "../plugins/calendar/js/jquery-1.11.3.min",
        'tools':"../plugins/calendar/js/jquery.tools.min",
        'toolbox':"../plugins/calendar/js/jquery.tools.toolbox.min.1.2.6",
        'tooltip':"../plugins/calendar/js/jquery.tools.tooltip.min.1.2.7",
        'jqueryui':'../plugins/jqueryui/js/jquery-ui.min',
        'autocomplete':'../plugins/bootstrap-autocomplete/js/bootstrap.autocomplete',
        'flexslider':'../plugins/flexslider/js/jquery.flexslider-min',
        'iscroll':'../plugins/iscroll/js/iscroll',
        'popwin':'../plugins/popwin/js/popWin',
        'pwd':'../plugins/password/js/pwd',
        'bootstrap':'../plugins/bootstrapv3/bootstrap/js/bootstrap',
        'datetimepicker':'../plugins/bootstrapv3/bootstrap/js/bootstrap-datetimepicker',
        'datetimepickerCN':'../plugins/bootstrapv3/bootstrap/js/locales/bootstrap-datetimepicker.zh-CN',
        "mouseWheel":"jquery.mousewheel",
       	"smoothScroll":"jquery.simplr.smoothscroll.min",
       	"jia":"http://v3.jiathis.com/code/jia",
        "fancybox":'../plugins/fancybox/js/jquery.fancybox',
        "fancybox-thumbs":'../plugins/fancybox/js/jquery.fancybox-thumbs',
        "jquery_form":'jquery.form',
        "wx":"http://res.wx.qq.com/open/js/jweixin-1.0.0",
        "jyyz":"http://static.geetest.com/static/js/geetest.0.0.0",
        "mslider":"../plugins/mslider/js/mslider",
        "iswiper":"../plugins/iswiper/js/idangerous.swiper",
        "iswiper.scroll":"../plugins/iswiper/js/idangerous.swiper.scrollbar",
        "swiper.animate":"../plugins/swiper/js/swiper.animate.min",
        "stellar":"../plugins/stellar/js/jquery.stellar.min",
        "lofSlider":"../plugins/slider/lof-slider",
        "easing":"../plugins/slider/jquery.easing",
        "mySwiper":"mySwiper",
        "ms":"mgslider",
        'mySwiperSpec':'../jasmine/spec/mySwiperSpec',
        'deapshare':'deepshare_v1.3.min',
        'boot':'../jasmine/lib/jasmine-core/boot',
        'jasmine':'../jasmine/lib/jasmine-core/jasmine',
        'jasmine-html':'../jasmine/lib/jasmine-core/jasmine-html',
        'player':'../jasmine/lib/jasmine-core/example/src/Player',
        'playerSpec':'../jasmine/lib/jasmine-core/example/spec/PlayerSpec',
        'locationControl':'locationControl',
        'recommendSw':'recommendSwiper',
        'floorNav':'floorNav',
        'fileReader':'fileReader',
        "jz":"jzslider",
        "sensorsdata":"sensorsdata.min" // 神策数据20170810
	}
});

